### PR TITLE
Change from master to main

### PR DESCRIPTION
**Pull request by kthyng**
Change from assuming principle branch is named "master" to "main", as is the new convention.

### CODE REVIEW

**Comment by jbusecke** [comment]
Thank you very much for the change @kthyng. Have you built a test project from the changed code? I really need some automatic way of testing the git part of this package automatically...

**Comment by kthyng** [comment]
I have though not sure how helpful they will be? I did make other changes too in setting it all up. Here are two:
* https://github.com/axiom-data-science/extract_model
* https://github.com/axiom-data-science/ocean_data_gateway

**Comment by jbusecke** [comment]
Very helpful indeed! I see that the CI etc are working, so I assume that this change is good to merge. 

Thanks again!

**Comment by kthyng** [comment]
Eep! I really hope I didn't mess anything up! I think I'll need to go through this process again soon and I'll take better notes so I can help integrate more changes. 

Thank you so much for making this package! It has really helped me get better up to speed on best practices.

**Comment by jbusecke** [comment]
Well we can always change things again, if they break hehe. And thanks for contributing back. I hope this project can evolve to become a 'living' version of crowdsourced best practices.

**Pull request merged**
